language: php

php:
  - 5.5

notifications:
  email:
    - chris@schalenborgh.be

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar self-update
    - php composer.phar install --dev