language: php

php:
  - 5.5

notifications:
  email:
    - chris@schalenborgh.be

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar self-update
    - php composer.phar install
    - travis_retry composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'